-- 코드를 입력하세요
SELECT C.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK_SALES A
    JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR C ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE YEAR(A.SALES_DATE) = 2022 AND MONTH(A.SALES_DATE) = 1
GROUP BY B.CATEGORY, B.AUTHOR_ID
ORDER BY C.AUTHOR_ID, CATEGORY DESC;


