SELECT SUM(A.SCORE) AS SCORE, B.EMP_NO ,B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_GRADE A
INNER JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO 
WHERE A.YEAR = '2022'
GROUP BY A.EMP_NO
ORDER BY SCORE DESC
LIMIT 1